defmodule UAInspector.ShortCode do
  @moduledoc """
  Utility module to handle (piwik) short codes.
  """

  @device_brands [
    { "3Q", "3Q" },
    { "AC", "Acer" },
    { "AI", "Airness" },
    { "AL", "Alcatel" },
    { "AN", "Arnova" },
    { "AO", "Amoi" },
    { "AP", "Apple" },
    { "AR", "Archos" },
    { "AU", "Asus" },
    { "AV", "Avvio" },
    { "AX", "Audiovox" },
    { "AY", "Axxion" },
    { "BB", "BBK" },
    { "BE", "Becker" },
    { "BI", "Bird" },
    { "BL", "Beetel" },
    { "BM", "Bmobile" },
    { "BN", "Barnes & Noble" },
    { "BO", "BangOlufsen" },
    { "BQ", "BenQ" },
    { "BS", "BenQ-Siemens" },
    { "BU", "Blu" },
    { "BX", "bq" },
    { "CA", "Cat" },
    { "CE", "Celkon" },
    { "CC", "ConCorde" },
    { "CH", "Cherry Mobile" },
    { "CK", "Cricket" },
    { "CL", "Compal" },
    { "CN", "CnM" },
    { "CM", "Crius Mea" },
    { "CR", "CreNova" },
    { "CT", "Capitel" },
    { "CQ", "Compaq" },
    { "CO", "Coolpad" },
    { "CW", "Cowon" },
    { "CU", "Cube" },
    { "CY", "Coby Kyros" },
    { "DA", "Danew" },
    { "DE", "Denver" },
    { "DB", "Dbtel" },
    { "DC", "DoCoMo" },
    { "DI", "Dicam" },
    { "DL", "Dell" },
    { "DM", "DMM" },
    { "DO", "Doogee" },
    { "DP", "Dopod" },
    { "EB", "E-Boda" },
    { "EC", "Ericsson" },
    { "EI", "Ezio" },
    { "EP", "Easypix" },
    { "ER", "Ericy" },
    { "ET", "eTouch" },
    { "EV", "Evertek" },
    { "EZ", "Ezze" },
    { "FL", "Fly" },
    { "FU", "Fujitsu" },
    { "GA", "Gateway" },
    { "GD", "Gemini" },
    { "GI", "Gionee" },
    { "GG", "Gigabyte" },
    { "GS", "Gigaset" },
    { "GO", "Google" },
    { "GR", "Gradiente" },
    { "GU", "Grundig" },
    { "HA", "Haier" },
    { "HP", "HP" },
    { "HT", "HTC" },
    { "HU", "Huawei" },
    { "HX", "Humax" },
    { "HY", "Hyrican" },
    { "IA", "Ikea" },
    { "IB", "iBall" },
    { "IY", "iBerry" },
    { "IK", "iKoMo" },
    { "IM", "i-mate" },
    { "IF", "Infinix" },
    { "IN", "Innostream" },
    { "II", "Inkti" },
    { "IX", "Intex" },
    { "IO", "i-mobile" },
    { "IQ", "INQ" },
    { "IT", "Intek" },
    { "IV", "Inverto" },
    { "IZ", "iTel" },
    { "JI", "Jiayu" },
    { "JO", "Jolla" },
    { "KA", "Karbonn" },
    { "KD", "KDDI" },
    { "KN", "Kindle" },
    { "KO", "Konka" },
    { "KT", "K-Touch" },
    { "KH", "KT-Tech" },
    { "KY", "Kyocera" },
    { "KZ", "Kazam" },
    { "LV", "Lava" },
    { "LA", "Lanix" },
    { "LC", "LCT" },
    { "LE", "Lenovo" },
    { "LN", "Lenco" },
    { "LG", "LG" },
    { "LO", "Loewe" },
    { "LM", "Logicom" },
    { "LX", "Lexibook" },
    { "MA", "Manta Multimedia" },
    { "MB", "Mobistel" },
    { "MD", "Medion" },
    { "ME", "Metz" },
    { "MX", "MEU" },
    { "MI", "MicroMax" },
    { "MK", "MediaTek" },
    { "MO", "Mio" },
    { "MM", "Mpman" },
    { "MR", "Motorola" },
    { "MS", "Microsoft" },
    { "MZ", "MSI" },
    { "MU", "Memup" },
    { "MT", "Mitsubishi" },
    { "MY", "MyPhone" },
    { "NE", "NEC" },
    { "NG", "NGM" },
    { "NI", "Nintendo" },
    { "NK", "Nokia" },
    { "NN", "Nikon" },
    { "NW", "Newgen" },
    { "NX", "Nexian" },
    { "OD", "Onda" },
    { "OP", "OPPO" },
    { "OR", "Orange" },
    { "OT", "O2" },
    { "OU", "OUYA" },
    { "OO", "Opsson" },
    { "PA", "Panasonic" },
    { "PE", "PEAQ" },
    { "PH", "Philips" },
    { "PL", "Polaroid" },
    { "PM", "Palm" },
    { "PO", "phoneOne" },
    { "PT", "Pantech" },
    { "PP", "PolyPad" },
    { "PS", "Positivo" },
    { "PR", "Prestigio" },
    { "QI", "Qilive" },
    { "QT", "Qtek" },
    { "QU", "Quechua" },
    { "OY", "Oysters" },
    { "RA", "Ramos" },
    { "RI", "Rikomagic" },
    { "RM", "RIM" },
    { "RO", "Rover" },
    { "SA", "Samsung" },
    { "SD", "Sega" },
    { "SE", "Sony Ericsson" },
    { "SF", "Softbank" },
    { "SX", "SFR" },
    { "SG", "Sagem" },
    { "SH", "Sharp" },
    { "SI", "Siemens" },
    { "SN", "Sendo" },
    { "SO", "Sony" },
    { "SP", "Spice" },
    { "SU", "SuperSonic" },
    { "SV", "Selevision" },
    { "SY", "Sanyo" },
    { "SM", "Symphony" },
    { "SR", "Smart" },
    { "ST", "Storex" },
    { "SZ", "Sumvision" },
    { "TA", "Tesla" },
    { "TC", "TCL" },
    { "TE", "Telit" },
    { "TH", "TiPhone" },
    { "TB", "Tecno Mobile" },
    { "TI", "TIANYU" },
    { "TL", "Telefunken" },
    { "TM", "T-Mobile" },
    { "TN", "Thomson" },
    { "T1", "Tolino" },
    { "TO", "Toplux" },
    { "TS", "Toshiba" },
    { "TT", "TechnoTrend" },
    { "TU", "Tunisie Telecom" },
    { "TV", "TVC" },
    { "TX", "TechniSat" },
    { "TZ", "teXet" },
    { "UT", "UTStarcom" },
    { "VD", "Videocon" },
    { "VE", "Vertu" },
    { "VI", "Vitelcom" },
    { "VK", "VK Mobile" },
    { "VS", "ViewSonic" },
    { "VT", "Vestel" },
    { "VO", "Voxtel" },
    { "VW", "Videoweb" },
    { "WB", "Web TV" },
    { "WE", "WellcoM" },
    { "WI", "Wiko" },
    { "WL", "Wolder" },
    { "WO", "Wonu" },
    { "WX", "Woxter" },
    { "XI", "Xiaomi" },
    { "XX", "Unknown" },
    { "YU", "Yuandao" },
    { "ZO", "Zonda" },
    { "ZP", "Zopo" },
    { "ZT", "ZTE" }
  ]

  for { short, long } <- @device_brands do
    def device_brand(unquote(short), :long),  do: unquote(long)
    def device_brand(unquote(long),  :short), do: unquote(short)
  end

  @doc """
  Converts device brands between their `:short` and `:long` representation.

  Unknown brands are returned unmodified.
  """
  @spec device_brand(brand :: String.t, format :: atom) :: String.t
  def device_brand(brand, _), do: brand
end
